<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <p>
      This is a private site map of me. To know more about me, <br>
      you may check out my
      <a href="https://github.com/mashirozx" target="_blank">GitHub</a>, 
      <a href="https://2heng.xin" target="_blank">Blog</a> or 
      <a href="https://mashiro.top" target="_blank">Notebook</a>.<br>
      This page was generated by <a href="https://nodejs.org/" class="green" target="_blank">Node.js</a> and <a href="https://vuejs.org" class="green" target="_blank">Vue.js</a>.
    </p>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: orange;
  font-size: bold
}
a.green {
  color: #42b983;
}
</style>
